package com.linkops.notification.domain;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    REVIEW_RECEIVED,
    PROVIDER_VERIFIED,
    PROVIDER_VERIFICATION_REJECTED,
    PROVIDER_VERIFICATION_REVOKED
}
