<script setup lang="ts">
import { Heart, MapPin, ShieldCheck, Star, Wrench } from 'lucide-vue-next'
import MarketplaceAvatar from '@/app/components/MarketplaceAvatar.vue'
import type { Provider } from '@/features/providers/types/provider'
import type { ServiceOffering } from '@/features/services/types/service'

interface Result { service: ServiceOffering; provider: Provider | null; photo: string | null }

defineProps<{ item: Result; variant: 'featured' | 'result'; saved: boolean }>()
defineEmits<{ favorite: []; open: [] }>()

function price(service: ServiceOffering) { return service.priceType === 'NEGOTIABLE' ? 'Preço negociável' : `Desde ${new Intl.NumberFormat('pt-MZ', { maximumFractionDigits: 0 }).format(service.price ?? 0)} MT` }
function rating(provider: Provider | null) { return provider?.averageRating ? provider.averageRating.toLocaleString('pt-MZ', { minimumFractionDigits: 1 }) : 'Novo' }
</script>

<template>
  <article v-if="variant === 'featured'" class="flex min-w-0 flex-col overflow-hidden rounded-lg border border-linkops-slate-200 bg-white">
    <div class="relative aspect-[1.85] shrink-0 bg-green-50"><img v-if="item.photo" :src="item.photo" :alt="item.service.title" class="absolute inset-0 size-full object-cover object-top" /><span v-else class="absolute inset-0 grid place-items-center text-linkops-green"><Wrench class="size-10" /></span><button type="button" class="absolute top-2 right-2 grid size-7 place-items-center rounded-full border-0 bg-white/95 text-slate-500 hover:text-red-500" :class="{ 'text-red-500': saved }" :aria-pressed="saved" aria-label="Guardar serviço nos favoritos" @click="$emit('favorite')"><Heart class="size-4" :class="{ 'fill-current': saved }" /></button></div>
    <div class="flex flex-1 flex-col gap-1.5 p-2.75 text-[11px]"><button type="button" class="truncate border-0 bg-transparent p-0 text-left text-[11px] font-medium text-deep-navy hover:text-linkops-green" @click="$emit('open')">{{ item.service.title }}</button><div class="flex min-w-0 items-center gap-1.5 text-[10px] text-linkops-slate-700"><MarketplaceAvatar :provider="item.provider" :fallback-name="item.service.providerName" class="size-5 text-[8px]" /><span class="min-w-0 flex-1 truncate">{{ item.service.providerName }}</span><span class="flex shrink-0 items-center gap-0.5 text-linkops-slate-500"><Star v-if="item.provider?.averageRating" class="size-3 fill-linkops-green text-linkops-green" />{{ rating(item.provider) }}</span></div><p class="m-0 flex items-center gap-1 text-[10px] text-linkops-slate-500"><MapPin class="size-3" />{{ item.service.city }}</p><div class="mt-auto flex items-center justify-between gap-1 pt-1"><strong class="text-xs font-medium text-linkops-green">{{ price(item.service) }}</strong><span v-if="item.provider?.verified" class="flex items-center gap-1 rounded bg-green-50 px-1 py-0.5 text-[9px] text-green-800"><ShieldCheck class="size-3" />Verificado</span></div></div>
  </article>
  <article v-else class="relative flex items-center gap-3 rounded-lg border border-linkops-slate-200 bg-white p-2.5 max-[760px]:flex-wrap">
    <img v-if="item.photo" :src="item.photo" :alt="item.service.title" class="size-22 shrink-0 rounded-md object-cover max-[600px]:size-20" /><span v-else class="grid size-22 shrink-0 place-items-center rounded-md bg-green-50 text-linkops-green max-[600px]:size-20"><Wrench class="size-8" /></span><div class="min-w-0 flex-1"><button type="button" class="block max-w-full truncate border-0 bg-transparent p-0 text-left text-xs font-medium text-deep-navy hover:text-linkops-green" @click="$emit('open')">{{ item.service.title }}</button><div class="mt-1 flex flex-wrap items-center gap-1.5 text-[10px] text-linkops-slate-500"><MarketplaceAvatar :provider="item.provider" :fallback-name="item.service.providerName" class="size-5 text-[8px]" /><span>{{ item.service.providerName }}</span><span class="flex items-center gap-0.5"><Star class="size-3 fill-linkops-green text-linkops-green" />{{ rating(item.provider) }}</span><span class="flex items-center gap-0.5"><MapPin class="size-3" />{{ item.service.city }}</span></div><p class="mt-1 mb-0 line-clamp-2 text-[10px] leading-4 text-linkops-slate-500">{{ item.service.description || 'Consulte o perfil para conhecer este serviço.' }}</p><span class="mt-1 inline-block rounded bg-slate-50 px-1.5 py-0.5 text-[9px] text-linkops-slate-500">{{ item.service.priceType === 'FIXED' ? 'Preço fixo' : 'Negociável' }}</span></div><div class="flex w-32 shrink-0 flex-col items-end gap-2 max-[760px]:ml-auto max-[500px]:w-auto"><button type="button" class="grid size-7 place-items-center rounded-full border-0 bg-transparent text-slate-500 hover:text-red-500" :class="{ 'text-red-500': saved }" :aria-pressed="saved" aria-label="Guardar serviço nos favoritos" @click="$emit('favorite')"><Heart class="size-4" :class="{ 'fill-current': saved }" /></button><strong class="text-xs font-medium text-linkops-green">{{ price(item.service) }}</strong><button type="button" class="rounded-md border border-linkops-green bg-white px-3 py-1 text-[10px] font-medium text-green-800 hover:bg-green-50" @click="$emit('open')">Ver perfil</button></div>
  </article>
</template>
